import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Preface from '@/components/Preface'
import Greeting from '@/components/Greeting'
import Mempelai from '@/components/Mempelai'
import Lokasi from '@/components/Lokasi'
import Protokol from '@/components/Protokol'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* <Preface /> */}
     <Greeting />
     <Mempelai />
     <Lokasi />
     <Protokol />
    </div>
  )
}
